version: '3.8'

services:
  sonarquest:
    build:
      context: .
      args:
        - VITE_SONARQUBE_URL=${VITE_SONARQUBE_URL}
        - VITE_SONARQUBE_TOKEN=${VITE_SONARQUBE_TOKEN}
        - VITE_SONARQUBE_ORGANIZATION=${VITE_SONARQUBE_ORGANIZATION}
        - VITE_USE_REAL_SONARQUBE=${VITE_USE_REAL_SONARQUBE:-true}
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    
  # Optional: Add your SonarQube instance here if running locally
  # sonarqube:
  #   image: sonarqube:community
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
  #   volumes:
  #     - sonarqube_data:/opt/sonarqube/data
  #     - sonarqube_logs:/opt/sonarqube/logs
  #     - sonarqube_extensions:/opt/sonarqube/extensions

# volumes:
#   sonarqube_data:
#   sonarqube_logs:
#   sonarqube_extensions: